# Generated by Django 5.1 on 2024-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0003_alter_guestbookentry_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookentry",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
