name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment variable for image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    
    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ env.IMAGE_TAG }}
      
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):latest
